import {blogPost} from './blogPost'
import {
  homeAboutSection,
  homeBlogSection,
  homeHeroSection,
  homePage,
  homeServicesSection,
} from './homePage'
import {service} from './service'
import {
  articleList,
  articleSection,
  callout,
  faq,
  framework,
  insightList,
  sources,
  tableOfContents,
  takeaways,
  tldr,
  useCase,
  vendorProfile,
} from './articleBlocks'
import {imageWithAlt, schemaThing, seoFields, simplePortableText} from './shared'
import {reusableButton, reusableComponents, reusableCtaSection} from './reusableComponents'
import {
  globalBrand,
  globalButton,
  globalContact,
  globalFooter,
  globalHeader,
  navigationChildItem,
  navigationItem,
  siteGlobals,
  socialLink,
} from './siteGlobals'
import {
  serviceCta,
  serviceImage,
  serviceIntro,
  serviceNarrative,
  serviceOffering,
  statCallout,
} from './serviceBlocks'
import {
  serviceCtaVideoSection,
  serviceFaqSection,
  serviceFeatureGridSection,
  serviceIndex,
  serviceProcessSection,
  serviceStatsMarqueeSection,
} from './serviceSections'

export const schemaTypes = [
  blogPost,
  homePage,
  service,
  imageWithAlt,
  schemaThing,
  reusableButton,
  reusableComponents,
  reusableCtaSection,
  siteGlobals,
  globalBrand,
  globalContact,
  globalHeader,
  globalFooter,
  globalButton,
  socialLink,
  navigationItem,
  navigationChildItem,
  seoFields,
  simplePortableText,
  homeHeroSection,
  homeServicesSection,
  homeAboutSection,
  homeBlogSection,
  articleSection,
  articleList,
  tldr,
  insightList,
  callout,
  takeaways,
  tableOfContents,
  faq,
  sources,
  framework,
  vendorProfile,
  useCase,
  serviceIntro,
  serviceNarrative,
  statCallout,
  serviceOffering,
  serviceCta,
  serviceImage,
  serviceIndex,
  serviceFeatureGridSection,
  serviceStatsMarqueeSection,
  serviceProcessSection,
  serviceCtaVideoSection,
  serviceFaqSection,
]
