import {blogPost} from './blogPost'
import {
  homeAboutSection,
  homeBlogSection,
  homeHeroSection,
  homePage,
  homeServicesSection,
} from './homePage'
import {service} from './service'
import {
  articleList,
  articleSection,
  callout,
  faq,
  framework,
  insightList,
  sources,
  tableOfContents,
  takeaways,
  tldr,
  useCase,
  vendorProfile,
} from './articleBlocks'
import {imageWithAlt, schemaThing, seoFields, simplePortableText} from './shared'
import {
  aboutPage,
  blogIndexPage,
  caseStudiesIndex,
  caseStudy,
  contactPage,
  faqPage,
  genericPage,
  notFoundPage,
  teamMember,
  testimonial,
} from './contentPages'
import {
  aboutContentSection,
  aboutHeroSection,
  blogSection,
  brandLogosSection,
  caseStudiesSection,
  contactForm,
  contactInputField,
  contactSection,
  ctaBarSection,
  ctaGallerySection,
  ctaVideoSection,
  faqItem,
  faqSection,
  featuresGridSection,
  heroSectionTwo,
  pricingSection,
  socialBarSection,
  statsItem,
  statsMarqueeSection,
  statsSection,
  teamSection,
  testimonialSection,
  videoConfig,
} from './pageSections'
import {reusableButton, reusableComponents, reusableCtaSection} from './reusableComponents'
import {
  globalBrand,
  globalButton,
  globalContact,
  globalAppManifest,
  globalForms,
  globalFooter,
  globalHeader,
  globalIndexing,
  globalOrganization,
  globalSeoDefaults,
  globalUiCopy,
  navigationChildItem,
  navigationItem,
  siteGlobals,
  socialLink,
} from './siteGlobals'
import {
  serviceCta,
  serviceImage,
  serviceIntro,
  serviceNarrative,
  serviceOffering,
  statCallout,
} from './serviceBlocks'
import {
  serviceCtaVideoSection,
  serviceFaqSection,
  serviceFeatureGridSection,
  serviceIndex,
  serviceProcessSection,
  serviceStatsMarqueeSection,
} from './serviceSections'

export const schemaTypes = [
  blogPost,
  homePage,
  service,
  imageWithAlt,
  schemaThing,
  reusableButton,
  reusableComponents,
  reusableCtaSection,
  siteGlobals,
  globalBrand,
  globalContact,
  globalHeader,
  globalFooter,
  globalButton,
  globalSeoDefaults,
  globalOrganization,
  globalIndexing,
  globalForms,
  globalUiCopy,
  globalAppManifest,
  socialLink,
  navigationItem,
  navigationChildItem,
  seoFields,
  simplePortableText,
  homeHeroSection,
  homeServicesSection,
  homeAboutSection,
  homeBlogSection,
  articleSection,
  articleList,
  tldr,
  insightList,
  callout,
  takeaways,
  tableOfContents,
  faq,
  sources,
  framework,
  vendorProfile,
  useCase,
  serviceIntro,
  serviceNarrative,
  statCallout,
  serviceOffering,
  serviceCta,
  serviceImage,
  serviceIndex,
  serviceFeatureGridSection,
  serviceStatsMarqueeSection,
  serviceProcessSection,
  serviceCtaVideoSection,
  serviceFaqSection,
  aboutPage,
  blogIndexPage,
  faqPage,
  contactPage,
  notFoundPage,
  genericPage,
  caseStudiesIndex,
  caseStudy,
  teamMember,
  testimonial,
  statsItem,
  faqItem,
  videoConfig,
  aboutContentSection,
  aboutHeroSection,
  statsSection,
  statsMarqueeSection,
  teamSection,
  testimonialSection,
  faqSection,
  featuresGridSection,
  contactInputField,
  contactForm,
  contactSection,
  ctaVideoSection,
  ctaGallerySection,
  ctaBarSection,
  heroSectionTwo,
  socialBarSection,
  brandLogosSection,
  pricingSection,
  caseStudiesSection,
  blogSection,
]
